---
- name: BMO
  hosts: all
  become: true

  roles:
    - role: system
      tags: system

    - role: artis3n.tailscale.machine
      tags: network

    - role: geerlingguy.pip
      tags: pip

    - role: docker
      tags:
        - docker
        - dockercore

    - role: portainer
      tags:
        - docker
        - portainer
