---
- name: bmo
  hosts: all
  become: true
  collections:
    - artis3n.tailscale

  roles:
    - role: system
      tags: system

    - role: artis3n.tailscale.machine
      tags: network

    - role: geerlingguy.pip
      tags: pip

    - role: docker
      tags:
        - docker
        - dockercore
