system_packages:
  - sudo
  - exfat-fuse
  - exfatprogs
  - curl

mounts:
  - src: /dev/sda1
    path: /mnt/bmo2

pip_install_packages:
  - name: docker

portainer_server_ip: bmo.lan
portainer_api_url: "http://{{ portainer_server_ip }}:9000"
portainer_admin_user: admin
#portainer_admin_password: (vault)
portainer_endpoint_id: "3"

tailscale_tags: ["server"]
