packages:
  - sudo
  - exfat-fuse
  - exfatprogs

mounts:
  - src: /dev/sda1
    path: /mnt/bmo2

pip_install_packages:
  - name: docker

server_ip: bmo.lan
portainer_api_url: "http://{{ server_ip }}:9000"

tailscale_tags: ["server"]
