system_packages:
  - sudo
  - exfat-fuse
  - exfatprogs
  - curl
  - systemd-resolved
  - samba

system_mounts:
  - src: "LABEL=External2TB"
    path: "/mnt/bmo2"

pip_install_packages:
  - name: docker

portainer_server_ip: bmo.cassowary-harmonic.ts.net
portainer_api_url: "http://{{ portainer_server_ip }}:9000"
portainer_admin_user: admin
portainer_endpoint_id: "3"

tailscale_tags: ["server"]
