$ANSIBLE_VAULT;1.1;AES256
65346435643763646361653638636433313165636531386162653039636534626365326136346434
3232626435613232303736373534643430613831666437620a666466333264333961656533363434
63303732613935623531336463386334323066356539663530313839393162373264383066343435
3234303334396532350a396335626434323732323765396638623264623561313932663664306637
34643332393130653537653836623536626532353364316238363137636466623363643832653966
34326236306136386137663930623264353861626161353963663464373562663538636537643735
38643838623863623330356361323139653664343362636263633033653936616535346135623836
33383835326232633232326437653132656265643962666336376565653064346630343133353938
30336431633064363330363030376565643035353331306231663739343163663462346133616636
65353665373630316330343830616563656433653838306234316339323437613761396462646264
37663161646166643661383865353965386538303534643966356165643165353836333562303831
64396433613263623639643630633934616536313630323263356265643037616166303737313235
32383033656162633463643138363838643439313939386238646565376634636137
