$ANSIBLE_VAULT;1.1;AES256
61633864656238393030653838333864613530376334363835313630333938343162336333396134
3661323331313665653036376162313861643739613633370a656436306265333034383434623431
39613037306133303233623433616434636232633032643261393565353831363863373663616464
6539613536316462650a383363303564623130383731656330663166356235643632363362366563
35663838383739316265633132613261643934393763313131643964323730373864373233313766
63663939343866363765373266653834396464356564396230663862323262633431623234333538
64353262336637303364383762373035373933623039323333316434353132346539663838353265
30323262653937646535633234393432633733363362656531363838636233643965663131356236
64353866343632656436643331363564363933616232393333356462323037373763366230623137
3963363062346561303635666235323362353464336462623438
