$ANSIBLE_VAULT;1.1;AES256
36356434313139616338353738393366396630663966383938636666316133633133656461643563
6261356335653335613333663664656232313835383430350a656363646532656339363231616661
31656363643932393731346564636365363065356638656533376237386137656532616238366436
3036373664633033390a316535356630346534313830383965656165666136653566653530336639
33343763333839636262633136613230663466623164613932643532633237343935346163373133
31623731366131326663613235633336636339633562323431633363636330656262303337633962
37356236346139373432383861353638663564366461306333643332323865616331653634653663
32373965383433666639663664666563326366383066353535383738303465346163323937316133
63323732363166653862336565386263663761383939366136323137323737373731386334353965
62663465623462343138613435343630313432666231306564313331366430336538626565313962
38613332633535373538623139366335636533326235323933353336323961636661383961343666
63636563356437643763
