---
- name: Ensure all necessary groups are created
  group:
    name: "{{ item }}"
  loop:
    - docker
    - samba
    - "{{ ansible_user }}"

- name: Ensure the non-root user is created
  user:
    name: "{{ ansible_user }}"
    password: "{{ ansible_user_password | password_hash('sha512') }}"
    groups:
      - sudo
      - docker
      - users
      - samba
    append: yes
    shell: "{{ shell }}"
    update_password: on_create

- name: Enable passwordless sudo for "{{ ansible_user }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"