- name: Create portainer folder under appdata
  ansible.builtin.file:
    path: "/appdata/portainer"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create portainer container
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    restart_policy: always
    published_ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /appdata/portainer:/data


- name: Create admin account in Portainer ("{{ portainer_admin_user }}")
  uri:
    url: "{{ portainer_api_url }}/api/users/admin/init"
    method: POST
    body_format: json
    headers:
      Content-Type: "application/json"
    body: '{"Username": "{{ portainer_admin_user }}", "Password": "{{ portainer_admin_password }}", "Role": 1}'
    status_code: 200, 409
  tags: portainer_admin
